apiVersion: v1
kind: Service
metadata:
  name: resultapp
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: resultapp
    tier: frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: resultapp
spec:
  template:
    metadata:
      labels:
        app: resultapp
        tier: frontend
    spec:
      containers:
      - name: resultapp
        image: surajd/resultapp
        ports:
        - containerPort: 80