apiVersion: v1
kind: Service
metadata:
  name: votingapp
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: votingapp
    tier: frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: votingapp
spec:
  template:
    metadata:
      labels:
        app: votingapp
        tier: frontend
    spec:
      containers:
      - name: votingapp
        image: votingapp
        ports:
        - containerPort: 80