apiVersion: v1
kind: ReplicationController
metadata:
  name: worker
spec:
  template:
    metadata:
      labels:
        app: worker
        tier: backend
    spec:
      containers:
      - name: worker
        image: worker